<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-CategoryDetail</name>
   <tag></tag>
   <elementGuidId>cf49c7ff-719b-4519-9547-87523d0658dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gh-cat&quot;]/option[text()='${paramCategoryDetail}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gh-cat&quot;]/option[text()='${paramCategoryDetail}']</value>
   </webElementProperties>
</WebElementEntity>
